kind: Service
apiVersion: v1
metadata:
  name: tcp-server
  namespace: tcp
spec:
  selector:
    app: tcp-server
  ports:
  - protocol: TCP
    name: tcp-8000
    appProtocol: TCP
    port: 8000
    targetPort: 8000
  - protocol: TCP
    name: tcp-5000
    appProtocol: TCP
    port: 5000
    targetPort: 5000